### ISSUE TITLE
Words in Appian 1.12.103 are missing @head values

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#1]
Hello @vgorman1 ! In Appian 1.11-14, sentence id 87, subdoc 1.12.103 --  starting from  https://github.com/vgorman1/Greek-Dependency-Trees/blob/764e7d9256883e8db1d8c208aab6d72ebfca4dd1/xml%20versions/Appian%20BC%201.11-14%20bu1.xml#L2384 -- the `@head` attributes of `word` elements are missing values, which means that the sentence is not treebanked. Is there a syntactical issue, or something else? Should this be corrected? The sentence seems reasonably normal: Τοῦ δ' ἐπιόντος ἔτους Σύλλας, καίπερ ῶν δικτάτωρ, ἐς ὑπόκρισιν ὅμως καὶ σχῆμα δημοκρατικῆς ἀρχῆς ὑπέστη καὶ ὕπατος αὖθις γενέσθαι σὺν Μετέλλῳ τῷ Εὐσεβεῖ.

**Comment by vgorman1** [comment]
Dear Neven,
There are some that just get missed.  I try to double-check that everything is labeled, but I miss some.  If you find any, like this one, point it out and I will go back and fix it.
I will fix Appian very shortly and upload a clean version in a little while.
Thanks!
Vanessa

Vanessa B. Gorman
Professor of Ancient History
Department of History
619 Oldfather Hall
University of Nebraska-Lincoln
Lincoln, NE 68588-0327
https://vgorman1.github.io/

**Comment by vgorman1** [comment]
Dear Neven,
I just recommitted all four Appian files, since I found some  relation=”” in each.
Cheers,
Vanessa

Vanessa B. Gorman
Professor of Ancient History
Department of History
619 Oldfather Hall
University of Nebraska-Lincoln
Lincoln, NE 68588-0327
https://vgorman1.github.io/

**Comment by nevenjovanovic** [comment]
@vgorman1 , here is a list of 19 files with (excluding Appian) where some sentences, 31 in all, are missing `@head` values:
```
aristotle-politics-book-2-bu2.xml
athen12-1-9-jan-15.xml
athen13-40-49-jan-15.xml
athen13-50-59-jan-15.xml
athen13-70-79-jan-15.xml
athen13-80-89-jan-15.xml
athen13-90-95-jan-15.xml
hdt-1-1-19-bu3.xml
hdt-1-170-189-bu2.xml
hdt-1-190-216-bu2.xml
hdt-1-80-99-bu5.xml
plato-apology-17a-42a.xml
polybius-10-1-10-bu1.xml
polybius-2-1-10-bu1.xml
polybius-9-1-20-bu1.xml
polybius-9-21-33-bu1.xml
thuc-1-61-80-bu3.xml
xen-cyr-1-1-2-bu1.xml
xen-cyr-1-3-4-bu1.xml
```
And here is a full list of those 31 sentences with missing `@head` values (file name, subdocument, id):
```
aristotle-politics-book-2-bu2.xml : 2.1264a : 133
aristotle-politics-book-2-bu2.xml : 2.1264b : 135
aristotle-politics-book-2-bu2.xml : 2.1267b : 248
aristotle-politics-book-2-bu2.xml : 2.1272a : 436
athen12-1-9-jan-15.xml : 12.3 : 28
athen12-1-9-jan-15.xml : 12.5 : 47
athen13-40-49-jan-15.xml : 13.47 : 151
athen13-40-49-jan-15.xml : 13.49 : 175
athen13-40-49-jan-15.xml : 13.49 : 194
athen13-50-59-jan-15.xml : 13.54 : 72
athen13-70-79-jan-15.xml : 13.75 : 84
athen13-70-79-jan-15.xml : 13.76 : 99
athen13-70-79-jan-15.xml : 13.79 : 132
athen13-80-89-jan-15.xml : 13.81 : 35
athen13-80-89-jan-15.xml : 13.88 : 152
athen13-90-95-jan-15.xml : 13.91 : 18
hdt-1-1-19-bu3.xml : 1.12 : 86
hdt-1-170-189-bu2.xml : 1.174 : 35
hdt-1-190-216-bu2.xml : 1.199 : 97
hdt-1-80-99-bu5.xml : 1.82.4 : 18
hdt-1-80-99-bu5.xml : 1.91.5 : 115
plato-apology-17a-42a.xml : 20b : 52
plato-apology-17a-42a.xml : 24c : 145
plato-apology-17a-42a.xml : 41a : 466
polybius-10-1-10-bu1.xml : 10.6.6 : 47
polybius-2-1-10-bu1.xml : 2.10.9 : 105
polybius-9-1-20-bu1.xml : 9.9.10 : 74
polybius-9-21-33-bu1.xml : 9.24.1 : 25
thuc-1-61-80-bu3.xml : 1.78.4 : 133
xen-cyr-1-1-2-bu1.xml : 1.2.8 : 56
xen-cyr-1-3-4-bu1.xml : 1.4.10 : 166
```

**Comment by nevenjovanovic** [comment]
I have listed the names from the Perseids repository https://github.com/perseids-publications/gorman-trees -- but I hope you will recognize the files.

**Comment by vgorman1** [comment]
Dear Neven,
I am working on these.  A number of them are already fixed.  A few (Athenaeus and Polybius especially) will take another day or two.  They were done in the pre-Arethusa system, and have some other problems I should fix at the same time.
The most up-to-date version is available through the link on my Github website: https://vgorman1.github.io/
Best wishes,
Vanessa

Vanessa B. Gorman
Professor of Ancient History
Department of History
619 Oldfather Hall
University of Nebraska-Lincoln
Lincoln, NE 68588-0327
https://vgorman1.github.io/

**Comment by nevenjovanovic** [comment]
Great to hear. When you have corrected everything, don't forget to close this issue!

**Comment by vgorman1** [comment]
I think I have corrected everything except the Athenaeus.  Again, that will take a while, since it is a mess.

**Comment by vgorman1** [comment]
I reloaded much better files of Athenaeus (both book 12 and 13).  They should be cleaner with valid POStags.
