### ISSUE TITLE
Why is Μάλιχος not dependent on the predicate ἀπεμνημόνευσεν?

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#10]
In Josephus Flavius:

https://github.com/vgorman1/Greek-Dependency-Trees/blob/8b81eb91438c361e9a1a710ec1c55cc9dc24101f/xml%20versions/josephus%20BJ%201.11-15%20bu1.xml#L246

I think Μάλιχος should be dependent on ἀπεμνημόνευσεν `<word id="8" form="ἀπεμνημόνευσεν" lemma="ἀπομνημονεύω" postag="v3saia---" relation="PRED_CO" head="12"/>`.

What am I getting wrong?

**Comment by vgorman1** [comment]
Since it is the subject of both PREDs, I hang it on the COORD.
