### ISSUE TITLE
The file demosthenes 50 tree.xml ends prematurely

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#11]
The XML file in https://github.com/vgorman1/Greek-Dependency-Trees/blob/85e11e396cdf966bc94de9d887010400a568804c/xml%20versions/demosthenes%2050%20tree.xml#L4566 ends in the middle of the sentence, and the tags are not closed, so the file does not validate. Something seems to have gone wrong.

**Comment by vgorman1** [comment]
Thank you for letting me know.  It is all there now.
