### ISSUE TITLE
Number after the closing XML tag makes XML document not valid

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#2]
In Plutarch treebank file fort. aut virt. bu1, there is a number "24" after the final closing tag in the XML: https://github.com/vgorman1/Greek-Dependency-Trees/blob/286b194e4f4e3f8e9ec24ad687054c53faeac79f/xml%20versions/plutarch%20alex%20fort%20aut%20virt%20bu1.xml#L11707
The number should be removed, because it makes the file not valid XML; my validator complains "Content is not allowed in trailing section.", and I cannot build the XML database (without removing the number first).

**Comment by vgorman1** [comment]
I fixed this.  I also removed a duplicate:  
plutarch alex fort aut virt bu2.htm is the better version of the same thing.  
plutarch alex fort aut virt bu1 is old and now removed.
