### ISSUE TITLE
Two postag attributes with AuxG value in Plato's Apology

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#3]
In file [xml versions/plato apology.xml](https://github.com/vgorman1/Greek-Dependency-Trees/blob/master/xml%20versions/plato%20apology.xml) there are two `AuxG` values in the `@postag` attribute:
```xml
<word id="14" form="—" lemma="" postag="AuxG" relation="AuxG" head="0"/>
<word id="31" form="—" lemma="" postag="AuxG" relation="AuxG" head="0"/>
```
Here `@lemma` and `@postag` values should be corrected to `lemma="—" postag="u--------"`, as elsewhere.

**Comment by vgorman1** [comment]
Fixed.  Thank you for finding these things!
