### ISSUE TITLE
Strange and possibly misspelled values in @relation attribute

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#4]
Here is a list of values in `@relation` attribute which should be checked (some codes might be misspelled), together with the file name and sentence `@id`.

Value | File | Sentence id
------- | ------ | -------
Auxx | plutarch alex fort aut virt bu2.xml | 231
AuxΓ, AuxΓ (in two places) | thuc 1 121-146 bu3.xml | 41
UNDEFINED_ExD1_SBJ_CO_ExD0_COORD | athen13 20-29 jan 15.xml | 117
nil | athen13 60-69 jan 15.xml | 121
nil | athen13 60-69 jan 15.xml | 124
nil | athen13 60-69 jan 15.xml | 126
AuxΞ | Aristotle Politics book 2 bu2.xml | 27
AuxX_ExD0_OBJ_AP_CO | athen12 1-9 jan 15.xml | 34
AuzY | demosthenes 18 201-275 bu1.xml | 64

**Comment by vgorman1** [comment]
Thanks Neven! I fixed four of the files.  The Athenaeus has lots of problems, since it was the first material I worked on and it was done in the old treebanking program.  I am going through it much more carefully and will load it when I am done. VG
