### ISSUE TITLE
Strange values in @postag (all hyphens)

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#5]
Here are some strange `@postag` values from Herodotus, Plutarch, and Polybius (excluding the Athenaeus files), all starting with the hyphen `-`; perhaps some of these postags could be identified?

File | Word
---- | -----
hdt 1 1-19 bu3 2019.xml | `<word id="16" form="Γυγάδας" postag="---------" lemma="" relation="PNOM" head="15"/>`
hdt 1 100-119 bu3 2019.xml | `<word id="8" form="Σασπείρων" postag="--------" lemma="" relation="ATR" head="7"/> `
hdt 1 120-149 bu2 2019.xml | `<word id="5" form="Εὐβοίες" postag="--------" lemma="" relation="ATR" head="4"/>`
hdt 1 190-216 bu2 2019.xml | `<word id="7" form="Ἀράξεω" postag="---------" lemma="" relation="ADV" head="5"/>`
plutarch lycurgus 1-15 bu4.xml | `<word id="29" form="Κνακιῶνος" postag="--------" lemma="" relation="ADV_CO" head="28"/>`
plutarch lycurgus 1-15 bu4.xml | `<word id="22" form="λ" postag="--------" lemma="" relation="ADV" head="20"/>`
plutarch lycurgus 1-15 bu4.xml | `<word id="24" form="δ" postag="--------" lemma="" relation="OBJ" head="25"/>`
plutarch lycurgus 16-31 bu2.xml | `<word id="16" form="ᾁδειν" postag="--------" lemma="" relation="OBJ" head="15"/>`
plutarch lycurgus 16-31 bu2.xml | `<word id="21" form="δεκατεσσάρων" postag="--------" lemma="" relation="ATR" head="22"/>`
plutarch lycurgus 16-31 bu2.xml | `<word id="6" form="Ἀντίωρον" postag="--------" lemma="" relation="ATR" head="1"/>`
polybius1 1-9 2017.xml | `<word xmlns:saxon="http://saxon.sf.net/" id="4" form="μεντολαδιατ" postag="---------" lemma="" relation="ExD" head="1"/>`

**Comment by vgorman1** [comment]
Fixed.
