### ISSUE TITLE
Kῦρος and Mένανδρος in `@lemma` do not start with Greek alphabet capitals

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#6]
In file `athen12 70-81 jan 15.xml`
https://github.com/vgorman1/Greek-Dependency-Trees/blob/d27f4ecb7d15ebc289d6b79e12bd9a474544ec41/xml%20versions/athen12%2070-81%20jan%2015.xml#L3331
the value `@lemma="Mένανδρος"`, with initial U+004D LATIN CAPITAL LETTER M, should be corrected to Μένανδρος with initial U+039C GREEK CAPITAL LETTER MU.

Likewise, in file `hdt 1 190-216 bu2 2019.xml`
https://github.com/vgorman1/Greek-Dependency-Trees/blob/d27f4ecb7d15ebc289d6b79e12bd9a474544ec41/xml%20versions/hdt%201%20190-216%20bu2%202019.xml#L4320
the value `@lemma="Kῦρος"` with initial U+004B LATIN CAPITAL LETTER K should be corrected to Κῦρος, with initial U+039A  GREEK CAPITAL LETTER KAPPA.

Check by pasting into, for example, https://www.fontspace.com/unicode/analyzer/ Unicode analyzer.

**Comment by vgorman1** [comment]
Good catch! I fixed the Herodotus.  I am working my way through Athenaeus, fixing a lot of things including the bad POStags.  I have the first three files done and uploaded (12.1-29).
