### ISSUE TITLE
Add suggestion on citing the archive

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#7]
I propose that you add to the README file of the repository, and also to the https://vgorman1.github.io/ , a suggestion on how to cite the treebank archive.

For a stable identifier (DOI and the like), you can connect the Github repository to Zenodo https://genr.eu/wp/cite/ or OSF https://help.osf.io/hc/en-us/articles/360019929813-Connect-GitHub-to-a-Project ; releases of your documents https://help.github.com/en/github/administering-a-repository/creating-releases then get a DOI and a stable URL.

This will also ensure that releases of the archive are preserved in a reasonable way, for a reasonable time, even if Github decide otherwise: https://about.zenodo.org/policies/ -- https://help.osf.io/hc/en-us/articles/360019737894-FAQs#what-if-you-run-out-of-funding-what-happens-to-my-data

**Comment by vgorman1** [comment]
Thanks, as always.  I have been thinking of getting a DOI, but have just gotten weighed down with the responsibilities of the semester.
VG

Vanessa B. Gorman
Professor, Ancient History
Dept. of History
University of Nebraska-Lincoln
619 Oldfather Hall
Lincoln, NE 68588-0327

**Comment by vgorman1** [comment]
I finally got a DOI and have added it to the README file.
