### ISSUE TITLE
Remove quotation mark from ‘Θεμιστοκλῆς in Thucydides 1, 121-146

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#8]
In file `thuc 1 121-146 bu3.xml` a quotation mark at the beginning of `@form` and `@lemma` values should be separated from the word Θεμιστοκλῆς:

https://github.com/vgorman1/Greek-Dependency-Trees/blob/728311e355c739384d60f738685fc0d570092668/xml%20versions/thuc%201%20121-146%20bu3.xml#L3859

**Comment by vgorman1** [comment]
Fixed.  It was a leftover quotation mark from the Loeb text.

**Comment by nevenjovanovic** [comment]
The `@lemma` value should be corrected too:
https://github.com/vgorman1/Greek-Dependency-Trees/blob/d4b41b8bf8aa6db9ece8c6d643750e2b812b049e/xml%20versions/thuc%201%20121-146%20bu3.xml#L3859
