### ISSUE TITLE
The Cassius Dio text is not completely annotated

### ISSUE THREAD

**Issue by nevenjovanovic** [vgorman1/Greek-Dependency-Trees#9]
In the Cassius Dio file, in sentences from the second one to the next to last one, the words are not annotated by lemma, morphology, or dependence.

https://github.com/vgorman1/Greek-Dependency-Trees/blob/d4b41b8bf8aa6db9ece8c6d643750e2b812b049e/xml%20versions/cassius%20dio%2050%20bu1.xml#L90

**Comment by vgorman1** [comment]
Oops.  Didn't mean to upload that one.  I just started it.
